### ISSUE TITLE
Redirect to www

### ISSUE THREAD

**Issue by Bergapalis** [Rob--W/https-by-default#18]
I've noticed that many sites or domains don't have a redirect from the https-domain to the https-www-subdomain. So I enter sleepeve.com. Then https://sleepeve.com/ opens. I get a warning that this site is not secure: 

`sleepeve.com uses an invalid security certificate.`

At first I was confused, but now I know that I have to add the www subdomain, and then it all works: https://www.sleepeve.com/

I've seen other errors: 

`Secure Connection Failed`

This one doesn't have an advanced button, so you have to figure this out yourself. 

While most users are probably pro enough to know how to handle this, it would be helpful to handle this differently. I'm not sure what the best way is, and I don't know how other users see this. Options are to display a warning page for this type of error, with a link to the www subdomain.

**Comment by Rob--W** [comment]
There is no rule that says that websites need to be accessed over `https://www.` . If servers can accept `https://www.example.com/` but not `https://example.com/`, then the server is misconfigured.

Is it really that common for you to need `www.`? I do personally not encounter such sites that often (over https).

If it is common enough, then I can consider adding an option to automatically try putting `www.` in front of the domain. But only if really necessary (since supporting this feature brings a new usability issue: you are being redirected to a site that might not even exist).

**Comment by Bergapalis** [comment]
It's clear that this is misconfiguration of the website, and not your fault. You can leave it as it is!
