### ISSUE TITLE
Include URL conversion without "www"

### ISSUE THREAD

**Issue by anthologist** [Rob--W/https-by-default#9]
Just tested it for the first time, good idea but it needs some enhancements. If I type a website "example.com" in the URL bar the http page is provided. If I type the full "www.example.com" the https one is retrieved.
Please include automatically the www during check?

**Comment by Rob--W** [comment]
Do you have an example? It is likely that the page itself is performing the redirect (so the server redirects to http even though the first request happens over https).

**Comment by anthologist** [comment]
Yes, these two examples have the behaviour described:
ansa.it --> www.ansa.it
vg247.it --> www.vg247.it

**Comment by Rob--W** [comment]
Since the server explicitly replied with a redirection to a non-https site, I will keep the current behavior as-is. There are too many sites which unconditionally redirect https-visitors to http, and rewriting such requests to automatically continue to https may lead to an infinite redirection loop.

 For example, `https://www.bbc.com` and `https://bbc.com` both redirect to `http://www.bbc.com`

If you want to use HTTPS on as many sites as possible (in addition to the sites that you manually type in the location bar), install the HTTPS Everywhere add-on from the EFF.
